import Head from 'next/head';
import { icons } from 'react-icons';
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillGithub, AiFillYoutube, AiFillLinkedin } from 'react-icons/ai'
import Image from "next/image";
import krish from "../public/teja.png";
import design from '../public/design.png';
import code from '../public/code.png';
import contents from '../public/content.png';
import p1 from '../public/pic1.png';
import pass from '../public/passwordz.png';
import hms from '../public/hms.png';
import iksa from '../public/iksa.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Teja Raivpudi Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40'>
        <section className="min-h-screen">
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-3xl font-burtons' >codewithKrish</h1>
              <ul className='flex items-center'>
                // <li><a href="https://codewithkrish02.github.io/blogs/" className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Blog</a></li>
              </ul>
            </nav>

            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl '>Teja Ravipudi</h2>
              <h3 className='text-2xl py-2 md:text-3xl'>Web Developer and Programming Enthusiast</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'> Create content on web programming and design. Join me now and lets code! </p>
            </div>

            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <a href='https://github.com/codewithKrish02' target={'_blank'}><AiFillGithub /></a>
              <a href='https://www.linkedin.com/in/tejaravipudi/' target={'_blank'}><AiFillLinkedin/></a>
              <a href='https://www.youtube.com/codewithKrish' target={'_blank'}><AiFillYoutube/></a>
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={krish} className='relative mx-auto' /> 
              {/* layout="fill" objectFit='cover' */}

            </div>
        </section>


        <section>
          <div>
            <h3 className='text-3xl py-1'>About</h3>
            <p className='text-md py-2 leading-8 text-grey-800'>Since the beginning of my journey as a Developer,
             I have learnt many frameworks and languages.
             I worked as a Intern in <span className='text-teal-500'>NetApp,Inc - India</span>. 
             I completed my Master's degree in <span className='text-teal-500'>Software Engineering</span>
              from Vellore Institute of Technology in India and am now pursuing a Master's in 
              <span className='text-teal-500'> Computer Science</span> at University of Texas at Dallas."</p>
             
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100} className='relative mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Skills I Learnt</h3>
              <p className='py-2'>Learning all the skills that are required for projects and videos</p>
              <p className='text-grey-800 py-1'>React JS</p>
              <p className='text-grey-800 py-1'>Django</p>
              <p className='text-grey-800 py-1'>REST API</p>
              <p className='text-grey-800 py-1'>Docker</p>
              <p className='text-grey-800 py-1'>Kali Linux</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100} className='relative mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Projects I Developed</h3>
              <p className='py-2'>Developed some projects using the skills i learnt.</p>
              <p className='text-grey-800 py-1'>AnnonyChat</p>
              <p className='text-grey-800 py-1'>HMS using Django</p>
              <p className='text-grey-800 py-1'>Passwordzz</p>
              <p className='text-grey-800 py-1'>Prediction of Student Placements</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={contents} width={100} height={100} className='relative mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Content I Created</h3>
              <p className='py-2'>Published videos on Web development,<br/> Computer programming and basics of Ethical Hacking.</p>
              <p className='text-grey-800 py-1'>SQL Injections</p>
              <p className='text-grey-800 py-1'>KeyLoggers</p>
              <p className='text-grey-800 py-1'>Login Automation</p>
              <p className='text-grey-800 py-1'>CSRF - Cross Site Request Forgery</p>
              <p className='text-grey-800 py-1'>HTML for Beginners</p>
            </div>
          </div>
          <div>
            <h3 className='text-3xl py-1'>Project Showcase</h3>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            {/* for images */}
            <div className='basis-1/3 flex-1'>
              <Image src={p1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
              <Image src={pass} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
              <Image src={hms} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/>
            </div>
          </div>
          
        </section>

      </main>
    </div>
  );
}
